### ISSUE TITLE
several instances of 'styled-components'

### ISSUE THREAD

**Issue by danestves** [AndreasFaust/react-strapi-img#1]
I'm working on a website that use `@emotion` and when installing `styled-components` this is the output of the console

![image](https://user-images.githubusercontent.com/31737273/108751697-e9f8e580-7518-11eb-876a-9e322cecb137.png)

Obviously it's because is two different libraries, but currently our stack use `@emotion`, how we can handle this kind of alerts/errors?

**Comment by AndreasFaust** [comment]
I have never used `@emotion`, but the API seems to be quite similar to `styled-components`. If this a larger project you have or a stack you want to reuse, I would recommend to download the `react-strapi-img`-code, replace all `styled components` with `@emotion` (I don’t think it’s so much effort) and maybe republish as new library (e.g. `react-strapi-emotion`).

**Comment by danestves** [comment]
Well, you have right on that, thanks for the clarification!
