### ISSUE TITLE
Images are showing with no-js

### ISSUE THREAD

**Issue by danestves** [AndreasFaust/react-strapi-img#2]
Hi! First thank you for the package, second i'm using it inside https://seeed.us/ this page that is build with NextJS, but if you inspect the images you can notice that says no-js i don't know if is anything with the framework itself or something like that, can you help me?

**Comment by danestves** [comment]
![image](https://user-images.githubusercontent.com/31737273/109357322-6ad91980-7858-11eb-9cff-dba13183a639.png)

As you can see i'm querying the `formats`, `url`, `width`, `height` and `alt` text but it's seems that it's not taking that

**Comment by danestves** [comment]
![image](https://user-images.githubusercontent.com/31737273/109357487-a7a51080-7858-11eb-918b-ee2a2df129ab.png)

And here i destructure all the result and put it there

**Comment by AndreasFaust** [comment]
Hello @danestves,

the class `no-js- + filename` is always set. If Javascript is deactivated, the `noscript`-tag is rendered, which hides the normal image and renders one, that works without JS. 

I do not understand which problem you have. Are you just confused about the `no-js`-class or does something not work?

**Comment by danestves** [comment]
Well if you see the site, the base64 is not rendered, and it's like is not taking the base64 from Strapi, and if you see the API https://sd-strapi-services.prod.seeed.us/pages?slug= you can see that the base64 is there

**Comment by AndreasFaust** [comment]
The prop `placeholder` had the wrong default (`false` instead of `true`). Upgrade to `0.2.3`, which I released just now and it should work.
Thanks for helping improve this plugin. If it is useful for you, consider supporting my open-source-work by staring it.
